= Parameters

The parent key for all of the following parameters is `kubevirt_operator`.


== `namespace`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
namespace:
  annotations: {} <1>
  labels: {} <2>
  name: syn-kubevirt-operator <3>
----
<1> Additional annotations.
<2> Additional labels.
<3> Namespace name.

Namespace configuraton.

If deploying Hyperconverged Cluster operator the namespace name will be hardcoded to `kubevirt-hyperconverged`.


== `olm`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
olm:
  enabled: false <1>
  channel: stable <2>
  resources: {} <3>
----
<1> Enable Hyperconverged operator.
<2> Hyperconveged olm release channel.
<3> Configure resources for operator.

Hyperconverged cluster operator configuration.

Deploying hyperconverged cluster operator will use OLM to install the operator.

This operator will manage all other operator contained in this component.

See https://github.com/kubevirt/hyperconverged-cluster-operator[Hyperconverged Cluster Operator Github] for documentation.


== `operators`

Enable / Configure operators.


=== `kubevirt`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
kubevirt:
  enabled: true <1>
  version: v1.1.1 <2>
----
<1> Enable KubeVirt operator.
<2> KubeVirt version.

KubeVirt operator configuration.


=== `data_importer`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
importer:
  enabled: true <1>
  version: v1.58.1 <2>
----
<1> Enable CDI operator.
<2> Containerized Data Importer version.

Containerized Data Importer operator configuration.


=== `network_addons`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
network_addons:
  enabled: true <1>
  version: v0.91.0 <2>
----
<1> Enable CNA operator.
<2> Cluster Network Addons version.

Cluster Network Addons operator configuration.


=== `hostpath_provisioner`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
network_addons:
  enabled: true <1>
  version: v0.18.0 <2>
----
<1> Enable Hostpath Provisioner perator.
<2> Cluster Network Addons version.

Hostpath Provisioner operator configuration.


== `config`

Configure instances.


=== `kubevirt`

[horizontal]
type:: dictionary
default:: See https://kubevirt.io/user-guide/operations/customize_components[KubeVirt Documentation].


=== `data_importer`

[horizontal]
type:: dictionary
default:: See https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md[Containerized Data Importer Documentation].


=== `network_addons`

[horizontal]
type:: dictionary
default:: See https://github.com/kubevirt/cluster-network-addons-operator[Cluster Network Addons Documentation].


=== `hostpath_provisioner`

[horizontal]
type:: dictionary
default:: See https://github.com/kubevirt/hostpath-provisioner-operator[Hostpath Provisioner Documentation].


== `vm`

Cluster scoped VM types and preferences.


=== `types`

[horizontal]
type:: dictionary
default:: {}

ClusterInstanceTypes configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


=== `preferences`

[horizontal]
type:: dictionary
default:: {}

ClusterInstancePreferences configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


== Example

[source,yaml]
----
kubevirt_operator:
  config:
    kubevirt:
      imagePullPolicy: IfNotPresent
      infra:
        nodeSelector:
          kubernetes.io/os: linux
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
      workload:
        nodeSelector:
          kubernetes.io/os: linux

    importer:
      config:
        featureGates:
          - HonorWaitForFirstConsumer
      imagePullPolicy: IfNotPresent
      infra:
        nodeSelector:
          kubernetes.io/os: linux
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
      workload:
        nodeSelector:
          kubernetes.io/os: linux

  cluster:
    types:
      small-4:
        cpu:
          guest: 2
        memory:
          quest: 4Gi
----
