= Parameters

The parent key for all of the following parameters is `kubevirt_operator`.

== `namespace`

[horizontal]
type:: string
default::
+
[source,yaml]
----
namespace:
  annotations: {}
  labels:
    kubevirt.io: ''
    pod-security.kubernetes.io/enforce: privileged
  name: syn-kubevirt-operator
----

The namespace in which to deploy this component.


== `operator`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
operator:
  replicas: 1
----

Configure operator.


== `importer`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
importer:
  version: v1.58.1 <1>
  namespace: <2>
    annotations: {}
    labels:
      cdi.kubevirt.io: ''
    name: syn-kubevirt-cdi
  replicas: 1 <3>
  spec: <4>
    config:
      featureGates:
        - HonorWaitForFirstConsumer
    imagePullPolicy: IfNotPresent
    infra:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
    workload:
      nodeSelector:
        kubernetes.io/os: linux
----
<1> Containerized Data Importer version.
<2> Configure CDI namespace.
<3> Configure CDI operator replicas.
<4> Define CDI instance.

See https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md[CDI Documentation] for specs.


== `kubevirt`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
kubevirt: {}
----

KubeVirt configuration, see https://kubevirt.io/user-guide/operations/customize_components/[KubeVirt Documentation] for specs.


== `instanceTypes`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
instanceTypes: {}
----

ClusterInstanceTypes configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


== `instancePreferences`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
instancePreferences: {}
----

ClusterInstanceTypes configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


== Example

[source,yaml]
----
kubevirt_operator:
  kubevirt:
    certificateRotateStrategy: {}
    configuration: {}
    customizeComponents: {}
    imagePullPolicy: IfNotPresent
    infra:
      replicas: 1
    workloadUpdateStrategy: {}

  instanceTypes:
    small-4:
      cpu:
        guest: 2
      memory:
        quest: 4Gi
----
