= Parameters

The parent key for all of the following parameters is `kubevirt_operator`.


== `operators`

Enable / Configure operators.


=== `hyperconverged`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
hyperconverged:
  enabled: false <1>
  channel: stable <2>
  namespace: <3>
    annotations: {}
    labels: {}
  resources: {} <4>
----
<1> Enable Hyperconverged operator.
<2> Hyperconveged olm release channel.
<3> Configure KubeVirt namespace.
<4> Configure resources for operator.

Hyperconverged cluster operator configuration.

Deploying hyperconverged cluster operator will use OLM to install the operator.

This operator will manage all other operator contained in this component.

See https://github.com/kubevirt/hyperconverged-cluster-operator[Hyperconverged Cluster Operator Github] for documentation.


=== `kubevirt`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
kubevirt:
  enabled: true <1>
  version: v1.1.1 <2>
  namespace: <3>
    annotations: {}
    labels:
      kubevirt.io: ''
      pod-security.kubernetes.io/enforce: privileged
    name: syn-kubevirt-operator
  replicas: 1 <4>
----
<1> Enable KubeVirt operator.
<2> KubeVirt version.
<3> Configure KubeVirt namespace.
<4> Configure KubeVirt operator replicas.

KubeVirt operator configuration.


=== `importer`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
importer:
  enabled: true <1>
  version: v1.58.1 <2>
  namespace: <3>
    annotations: {}
    labels:
      cdi.kubevirt.io: ''
    name: syn-kubevirt-cdi
  replicas: 1 <4>
----
<1> Enable CDI operator.
<2> Containerized Data Importer version.
<3> Configure CDI namespace.
<4> Configure CDI operator replicas.

Containerized Data Importer operator configuration.


== `config`

Configure instances.


=== `kubevirt`

[horizontal]
type:: dictionary
default:: See https://kubevirt.io/user-guide/operations/customize_components[KubeVirt Documentation].


=== `importer`

[horizontal]
type:: dictionary
default:: See https://github.com/kubevirt/containerized-data-importer/blob/main/doc/cdi-config.md[CDI Documentation].


== `cluster`

Cluster scoped VM types and preferences.


=== `types`

[horizontal]
type:: dictionary
default:: {}

ClusterInstanceTypes configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


=== `preferences`

[horizontal]
type:: dictionary
default:: {}

ClusterInstancePreferences configuration, see https://kubevirt.io/user-guide/virtual_machines/instancetypes/[KubeVirt Documentation] for specs.


== Example

[source,yaml]
----
kubevirt_operator:
  config:
    kubevirt:
      imagePullPolicy: IfNotPresent
      infra:
        nodeSelector:
          kubernetes.io/os: linux
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
      workload:
        nodeSelector:
          kubernetes.io/os: linux

    importer:
      config:
        featureGates:
          - HonorWaitForFirstConsumer
      imagePullPolicy: IfNotPresent
      infra:
        nodeSelector:
          kubernetes.io/os: linux
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
      workload:
        nodeSelector:
          kubernetes.io/os: linux

  cluster:
    types:
      small-4:
        cpu:
          guest: 2
        memory:
          quest: 4Gi
----
